deploy:
  needs: build
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main'

  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Start SSH agent and add SSH key
      run: |
        eval "$(ssh-agent -s)"
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Pull Docker image on server and restart container
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/my-app:latest
      run: |
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << EOF
          docker pull $IMAGE_NAME
          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name my-app -p 80:80 $IMAGE_NAME

